
name: Ryans Sample

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
   inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo "Testing!"
    
  build:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: ls -la

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          touch random
          echo "Hello" >> random
          cat random
  
  deploy:
    runs-on: ubuntu-latest

    needs: build

    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
